/* tslint:disable */
/* eslint-disable */
/**
 * Stadia Maps Geospatial APIs
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).
 *
 * The version of the OpenAPI document: 4.1.0
 * Contact: support@stadiamaps.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManeuverSignElement
 */
export interface ManeuverSignElement {
    /**
     * The interchange sign text (varies based on the context; see the `maneuverSign` schema).
     * @type {string}
     * @memberof ManeuverSignElement
     */
    text: string;
    /**
     * True if the sign is a route number.
     * @type {boolean}
     * @memberof ManeuverSignElement
     */
    isRouteNumber?: boolean;
    /**
     * The frequency of this sign element within a set a consecutive signs.
     * @type {number}
     * @memberof ManeuverSignElement
     */
    consecutiveCount?: number;
}

/**
 * Check if a given object implements the ManeuverSignElement interface.
 */
export function instanceOfManeuverSignElement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "text" in value;

    return isInstance;
}

export function ManeuverSignElementFromJSON(json: any): ManeuverSignElement {
    return ManeuverSignElementFromJSONTyped(json, false);
}

export function ManeuverSignElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManeuverSignElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': json['text'],
        'isRouteNumber': !exists(json, 'is_route_number') ? undefined : json['is_route_number'],
        'consecutiveCount': !exists(json, 'consecutive_count') ? undefined : json['consecutive_count'],
    };
}

export function ManeuverSignElementToJSON(value?: ManeuverSignElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'is_route_number': value.isRouteNumber,
        'consecutive_count': value.consecutiveCount,
    };
}

