/* tslint:disable */
/* eslint-disable */
/**
 * Stadia Maps Geospatial APIs
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).
 *
 * The version of the OpenAPI document: 4.1.0
 * Contact: support@stadiamaps.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinate } from './Coordinate';
import {
    CoordinateFromJSON,
    CoordinateFromJSONTyped,
    CoordinateToJSON,
} from './Coordinate';
import type { CostingModel } from './CostingModel';
import {
    CostingModelFromJSON,
    CostingModelFromJSONTyped,
    CostingModelToJSON,
} from './CostingModel';
import type { CostingOptions } from './CostingOptions';
import {
    CostingOptionsFromJSON,
    CostingOptionsFromJSONTyped,
    CostingOptionsToJSON,
} from './CostingOptions';
import type { ValhallaLanguages } from './ValhallaLanguages';
import {
    ValhallaLanguagesFromJSON,
    ValhallaLanguagesFromJSONTyped,
    ValhallaLanguagesToJSON,
} from './ValhallaLanguages';

/**
 * 
 * @export
 * @interface NearestRoadsRequest
 */
export interface NearestRoadsRequest {
    /**
     * 
     * @type {string}
     * @memberof NearestRoadsRequest
     */
    units?: NearestRoadsRequestUnitsEnum;
    /**
     * 
     * @type {ValhallaLanguages}
     * @memberof NearestRoadsRequest
     */
    language?: ValhallaLanguages;
    /**
     * The level of directional narrative to include. Locations and times will always be returned, but narrative generation verbosity can be controlled with this parameter.
     * @type {string}
     * @memberof NearestRoadsRequest
     */
    directionsType?: NearestRoadsRequestDirectionsTypeEnum;
    /**
     * An identifier to disambiguate requests (echoed by the server).
     * @type {string}
     * @memberof NearestRoadsRequest
     */
    id?: string;
    /**
     * 
     * @type {Array<Coordinate>}
     * @memberof NearestRoadsRequest
     */
    locations: Array<Coordinate>;
    /**
     * 
     * @type {CostingModel}
     * @memberof NearestRoadsRequest
     */
    costing: CostingModel;
    /**
     * 
     * @type {CostingOptions}
     * @memberof NearestRoadsRequest
     */
    costingOptions?: CostingOptions;
    /**
     * 
     * @type {boolean}
     * @memberof NearestRoadsRequest
     */
    verbose?: boolean;
}


/**
 * @export
 */
export const NearestRoadsRequestUnitsEnum = {
    Km: 'km',
    Mi: 'mi'
} as const;
export type NearestRoadsRequestUnitsEnum = typeof NearestRoadsRequestUnitsEnum[keyof typeof NearestRoadsRequestUnitsEnum];

/**
 * @export
 */
export const NearestRoadsRequestDirectionsTypeEnum = {
    None: 'none',
    Maneuvers: 'maneuvers',
    Instructions: 'instructions'
} as const;
export type NearestRoadsRequestDirectionsTypeEnum = typeof NearestRoadsRequestDirectionsTypeEnum[keyof typeof NearestRoadsRequestDirectionsTypeEnum];


/**
 * Check if a given object implements the NearestRoadsRequest interface.
 */
export function instanceOfNearestRoadsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "locations" in value;
    isInstance = isInstance && "costing" in value;

    return isInstance;
}

export function NearestRoadsRequestFromJSON(json: any): NearestRoadsRequest {
    return NearestRoadsRequestFromJSONTyped(json, false);
}

export function NearestRoadsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearestRoadsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'units': !exists(json, 'units') ? undefined : json['units'],
        'language': !exists(json, 'language') ? undefined : ValhallaLanguagesFromJSON(json['language']),
        'directionsType': !exists(json, 'directions_type') ? undefined : json['directions_type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'locations': ((json['locations'] as Array<any>).map(CoordinateFromJSON)),
        'costing': CostingModelFromJSON(json['costing']),
        'costingOptions': !exists(json, 'costing_options') ? undefined : CostingOptionsFromJSON(json['costing_options']),
        'verbose': !exists(json, 'verbose') ? undefined : json['verbose'],
    };
}

export function NearestRoadsRequestToJSON(value?: NearestRoadsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'units': value.units,
        'language': ValhallaLanguagesToJSON(value.language),
        'directions_type': value.directionsType,
        'id': value.id,
        'locations': ((value.locations as Array<any>).map(CoordinateToJSON)),
        'costing': CostingModelToJSON(value.costing),
        'costing_options': CostingOptionsToJSON(value.costingOptions),
        'verbose': value.verbose,
    };
}

