/* tslint:disable */
/* eslint-disable */
/**
 * Stadia Maps Geospatial APIs
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).
 *
 * The version of the OpenAPI document: 4.1.0
 * Contact: support@stadiamaps.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CostingModel } from './CostingModel';
import {
    CostingModelFromJSON,
    CostingModelFromJSONTyped,
    CostingModelToJSON,
} from './CostingModel';
import type { CostingOptions } from './CostingOptions';
import {
    CostingOptionsFromJSON,
    CostingOptionsFromJSONTyped,
    CostingOptionsToJSON,
} from './CostingOptions';
import type { RoutingWaypoint } from './RoutingWaypoint';
import {
    RoutingWaypointFromJSON,
    RoutingWaypointFromJSONTyped,
    RoutingWaypointToJSON,
} from './RoutingWaypoint';

/**
 * 
 * @export
 * @interface RouteRequestAllOf
 */
export interface RouteRequestAllOf {
    /**
     * An identifier to disambiguate requests (echoed by the server).
     * @type {string}
     * @memberof RouteRequestAllOf
     */
    id?: string;
    /**
     * 
     * @type {Array<RoutingWaypoint>}
     * @memberof RouteRequestAllOf
     */
    locations?: Array<RoutingWaypoint>;
    /**
     * 
     * @type {CostingModel}
     * @memberof RouteRequestAllOf
     */
    costing?: CostingModel;
    /**
     * 
     * @type {CostingOptions}
     * @memberof RouteRequestAllOf
     */
    costingOptions?: CostingOptions;
    /**
     * 
     * @type {Array<RoutingWaypoint>}
     * @memberof RouteRequestAllOf
     */
    avoidLocations?: Array<RoutingWaypoint>;
    /**
     * One or multiple exterior rings of polygons in the form of nested JSON arrays. Roads intersecting these rings will be avoided during path finding. Open rings will be closed automatically.
     * @type {Array<Array<Array<number>>>}
     * @memberof RouteRequestAllOf
     */
    avoidPolygons?: Array<Array<Array<number>>>;
}

/**
 * Check if a given object implements the RouteRequestAllOf interface.
 */
export function instanceOfRouteRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RouteRequestAllOfFromJSON(json: any): RouteRequestAllOf {
    return RouteRequestAllOfFromJSONTyped(json, false);
}

export function RouteRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'locations': !exists(json, 'locations') ? undefined : ((json['locations'] as Array<any>).map(RoutingWaypointFromJSON)),
        'costing': !exists(json, 'costing') ? undefined : CostingModelFromJSON(json['costing']),
        'costingOptions': !exists(json, 'costing_options') ? undefined : CostingOptionsFromJSON(json['costing_options']),
        'avoidLocations': !exists(json, 'avoid_locations') ? undefined : ((json['avoid_locations'] as Array<any>).map(RoutingWaypointFromJSON)),
        'avoidPolygons': !exists(json, 'avoid_polygons') ? undefined : json['avoid_polygons'],
    };
}

export function RouteRequestAllOfToJSON(value?: RouteRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'locations': value.locations === undefined ? undefined : ((value.locations as Array<any>).map(RoutingWaypointToJSON)),
        'costing': CostingModelToJSON(value.costing),
        'costing_options': CostingOptionsToJSON(value.costingOptions),
        'avoid_locations': value.avoidLocations === undefined ? undefined : ((value.avoidLocations as Array<any>).map(RoutingWaypointToJSON)),
        'avoid_polygons': value.avoidPolygons,
    };
}

