/* tslint:disable */
/* eslint-disable */
/**
 * Stadia Maps Geospatial APIs
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).
 *
 * The version of the OpenAPI document: 4.1.0
 * Contact: support@stadiamaps.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CostingOptions } from './CostingOptions';
import {
    CostingOptionsFromJSON,
    CostingOptionsFromJSONTyped,
    CostingOptionsToJSON,
} from './CostingOptions';
import type { MapMatchCostingModel } from './MapMatchCostingModel';
import {
    MapMatchCostingModelFromJSON,
    MapMatchCostingModelFromJSONTyped,
    MapMatchCostingModelToJSON,
} from './MapMatchCostingModel';
import type { MapMatchWaypoint } from './MapMatchWaypoint';
import {
    MapMatchWaypointFromJSON,
    MapMatchWaypointFromJSONTyped,
    MapMatchWaypointToJSON,
} from './MapMatchWaypoint';
import type { ValhallaLanguages } from './ValhallaLanguages';
import {
    ValhallaLanguagesFromJSON,
    ValhallaLanguagesFromJSONTyped,
    ValhallaLanguagesToJSON,
} from './ValhallaLanguages';

/**
 * 
 * @export
 * @interface BaseTraceRequest
 */
export interface BaseTraceRequest {
    /**
     * 
     * @type {string}
     * @memberof BaseTraceRequest
     */
    units?: BaseTraceRequestUnitsEnum;
    /**
     * 
     * @type {ValhallaLanguages}
     * @memberof BaseTraceRequest
     */
    language?: ValhallaLanguages;
    /**
     * The level of directional narrative to include. Locations and times will always be returned, but narrative generation verbosity can be controlled with this parameter.
     * @type {string}
     * @memberof BaseTraceRequest
     */
    directionsType?: BaseTraceRequestDirectionsTypeEnum;
    /**
     * An identifier to disambiguate requests (echoed by the server).
     * @type {string}
     * @memberof BaseTraceRequest
     */
    id?: string;
    /**
     * REQUIRED if `encoded_polyline` is not present. Note that `break` type locations are only supported when `shape_match` is set to `map_match`.
     * @type {Array<MapMatchWaypoint>}
     * @memberof BaseTraceRequest
     */
    shape?: Array<MapMatchWaypoint>;
    /**
     * REQUIRED if `shape` is not present. An encoded polyline (https://developers.google.com/maps/documentation/utilities/polylinealgorithm). Note that the polyline must be encoded with 6 digits of precision rather than the usual 5.
     * @type {string}
     * @memberof BaseTraceRequest
     */
    encodedPolyline?: string;
    /**
     * 
     * @type {MapMatchCostingModel}
     * @memberof BaseTraceRequest
     */
    costing: MapMatchCostingModel;
    /**
     * 
     * @type {CostingOptions}
     * @memberof BaseTraceRequest
     */
    costingOptions?: CostingOptions;
    /**
     * Three snapping modes provide some control over how the map matching occurs. `edge_walk` is fast, but requires extremely precise data that matches the route graph almost perfectly. `map_snap` can handle significantly noisier data, but is very expensive. `walk_or_snap`, the default, tries to use edge walking first and falls back to map matching if edge walking fails.
     * In general, you should not need to change this parameter unless you want to trace a multi-leg route with multiple `break` locations in the `shape`.
     * @type {string}
     * @memberof BaseTraceRequest
     */
    shapeMatch?: BaseTraceRequestShapeMatchEnum;
}


/**
 * @export
 */
export const BaseTraceRequestUnitsEnum = {
    Km: 'km',
    Mi: 'mi'
} as const;
export type BaseTraceRequestUnitsEnum = typeof BaseTraceRequestUnitsEnum[keyof typeof BaseTraceRequestUnitsEnum];

/**
 * @export
 */
export const BaseTraceRequestDirectionsTypeEnum = {
    None: 'none',
    Maneuvers: 'maneuvers',
    Instructions: 'instructions'
} as const;
export type BaseTraceRequestDirectionsTypeEnum = typeof BaseTraceRequestDirectionsTypeEnum[keyof typeof BaseTraceRequestDirectionsTypeEnum];

/**
 * @export
 */
export const BaseTraceRequestShapeMatchEnum = {
    EdgeWalk: 'edge_walk',
    MapSnap: 'map_snap',
    WalkOrSnap: 'walk_or_snap'
} as const;
export type BaseTraceRequestShapeMatchEnum = typeof BaseTraceRequestShapeMatchEnum[keyof typeof BaseTraceRequestShapeMatchEnum];


/**
 * Check if a given object implements the BaseTraceRequest interface.
 */
export function instanceOfBaseTraceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "costing" in value;

    return isInstance;
}

export function BaseTraceRequestFromJSON(json: any): BaseTraceRequest {
    return BaseTraceRequestFromJSONTyped(json, false);
}

export function BaseTraceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseTraceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'units': !exists(json, 'units') ? undefined : json['units'],
        'language': !exists(json, 'language') ? undefined : ValhallaLanguagesFromJSON(json['language']),
        'directionsType': !exists(json, 'directions_type') ? undefined : json['directions_type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'shape': !exists(json, 'shape') ? undefined : ((json['shape'] as Array<any>).map(MapMatchWaypointFromJSON)),
        'encodedPolyline': !exists(json, 'encoded_polyline') ? undefined : json['encoded_polyline'],
        'costing': MapMatchCostingModelFromJSON(json['costing']),
        'costingOptions': !exists(json, 'costing_options') ? undefined : CostingOptionsFromJSON(json['costing_options']),
        'shapeMatch': !exists(json, 'shape_match') ? undefined : json['shape_match'],
    };
}

export function BaseTraceRequestToJSON(value?: BaseTraceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'units': value.units,
        'language': ValhallaLanguagesToJSON(value.language),
        'directions_type': value.directionsType,
        'id': value.id,
        'shape': value.shape === undefined ? undefined : ((value.shape as Array<any>).map(MapMatchWaypointToJSON)),
        'encoded_polyline': value.encodedPolyline,
        'costing': MapMatchCostingModelToJSON(value.costing),
        'costing_options': CostingOptionsToJSON(value.costingOptions),
        'shape_match': value.shapeMatch,
    };
}

