/* tslint:disable */
/* eslint-disable */
/**
 * Stadia Maps Geospatial APIs
 * The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).
 *
 * The version of the OpenAPI document: 4.1.0
 * Contact: support@stadiamaps.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinate } from './Coordinate';
import {
    CoordinateFromJSON,
    CoordinateFromJSONTyped,
    CoordinateToJSON,
} from './Coordinate';
import type { CostingModel } from './CostingModel';
import {
    CostingModelFromJSON,
    CostingModelFromJSONTyped,
    CostingModelToJSON,
} from './CostingModel';
import type { CostingOptions } from './CostingOptions';
import {
    CostingOptionsFromJSON,
    CostingOptionsFromJSONTyped,
    CostingOptionsToJSON,
} from './CostingOptions';

/**
 * 
 * @export
 * @interface NearestRoadsRequestAllOf
 */
export interface NearestRoadsRequestAllOf {
    /**
     * An identifier to disambiguate requests (echoed by the server).
     * @type {string}
     * @memberof NearestRoadsRequestAllOf
     */
    id?: string;
    /**
     * 
     * @type {Array<Coordinate>}
     * @memberof NearestRoadsRequestAllOf
     */
    locations?: Array<Coordinate>;
    /**
     * 
     * @type {CostingModel}
     * @memberof NearestRoadsRequestAllOf
     */
    costing?: CostingModel;
    /**
     * 
     * @type {CostingOptions}
     * @memberof NearestRoadsRequestAllOf
     */
    costingOptions?: CostingOptions;
    /**
     * 
     * @type {boolean}
     * @memberof NearestRoadsRequestAllOf
     */
    verbose?: boolean;
}

/**
 * Check if a given object implements the NearestRoadsRequestAllOf interface.
 */
export function instanceOfNearestRoadsRequestAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NearestRoadsRequestAllOfFromJSON(json: any): NearestRoadsRequestAllOf {
    return NearestRoadsRequestAllOfFromJSONTyped(json, false);
}

export function NearestRoadsRequestAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NearestRoadsRequestAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'locations': !exists(json, 'locations') ? undefined : ((json['locations'] as Array<any>).map(CoordinateFromJSON)),
        'costing': !exists(json, 'costing') ? undefined : CostingModelFromJSON(json['costing']),
        'costingOptions': !exists(json, 'costing_options') ? undefined : CostingOptionsFromJSON(json['costing_options']),
        'verbose': !exists(json, 'verbose') ? undefined : json['verbose'],
    };
}

export function NearestRoadsRequestAllOfToJSON(value?: NearestRoadsRequestAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'locations': value.locations === undefined ? undefined : ((value.locations as Array<any>).map(CoordinateToJSON)),
        'costing': CostingModelToJSON(value.costing),
        'costing_options': CostingOptionsToJSON(value.costingOptions),
        'verbose': value.verbose,
    };
}

